// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThePerfectBatch.Data;

namespace ThePerfectBatch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ThePerfectBatch.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new { Id = "00000000-ffff-ffff-ffff-ffffffffffff", AccessFailedCount = 0, ConcurrencyStamp = "a41d3169-17c1-451d-b8ec-f597dda662ed", Email = "mr.mcconnell@internet.com", EmailConfirmed = true, FirstName = "Ricky", LastName = "McConnell", LockoutEnabled = false, NormalizedEmail = "MR.MCCONNELL@INTERNET.COM", PasswordHash = "AQAAAAEAACcQAAAAEJhwU9RH2tZ+Oy+uCP5N8JbiAJVrFsWT3Oh8K8LbqmkV5dgFZ1m7ngTiYmaglBnTjg==", PhoneNumberConfirmed = false, SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577", TwoFactorEnabled = false }
                    );
                });

            modelBuilder.Entity("ThePerfectBatch.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Quantity")
                        .IsRequired();

                    b.Property<int>("RecipeId");

                    b.HasKey("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new { IngredientId = 1, Name = "Egg", Quantity = "1", RecipeId = 1 },
                        new { IngredientId = 2, Name = "Vanilla Extract", Quantity = "1 Tsp", RecipeId = 1 },
                        new { IngredientId = 3, Name = "Cinnimon Grounds", Quantity = "1/2 Tsp", RecipeId = 1 },
                        new { IngredientId = 4, Name = "Milk", Quantity = "1/4 Cup of Milk", RecipeId = 1 },
                        new { IngredientId = 5, Name = "Bread", Quantity = "4 Slices", RecipeId = 1 },
                        new { IngredientId = 6, Name = "Chickpea Flour", Quantity = "1 Cup", RecipeId = 2 },
                        new { IngredientId = 7, Name = "Water", Quantity = "1 and 1/4 Cups", RecipeId = 2 },
                        new { IngredientId = 8, Name = "Lemon Juice", Quantity = "1 Tbsp", RecipeId = 2 },
                        new { IngredientId = 9, Name = "Salt", Quantity = "1/2 Tsp", RecipeId = 2 },
                        new { IngredientId = 10, Name = "Bread", Quantity = "2 Slices", RecipeId = 3 },
                        new { IngredientId = 11, Name = "Butter", Quantity = "1 Tbsp", RecipeId = 3 },
                        new { IngredientId = 12, Name = "Cheese of Choice", Quantity = "2 Slices", RecipeId = 3 },
                        new { IngredientId = 13, Name = "Skinless Chicken Breast", Quantity = "4", RecipeId = 4 },
                        new { IngredientId = 14, Name = "Salt and Pepper", Quantity = "To Taste", RecipeId = 4 },
                        new { IngredientId = 15, Name = "Eggs", Quantity = "2", RecipeId = 4 },
                        new { IngredientId = 16, Name = "Bread Crumbs", Quantity = "1 and 1/4 Cup", RecipeId = 4 },
                        new { IngredientId = 17, Name = "Grated Parmesean Cheese", Quantity = "1/2 Cup", RecipeId = 4 },
                        new { IngredientId = 18, Name = "Flour", Quantity = "2 Tbsp", RecipeId = 4 },
                        new { IngredientId = 19, Name = "Olive Oil for Frying", Quantity = "1 Cup", RecipeId = 4 },
                        new { IngredientId = 20, Name = "Tomato Sauce", Quantity = "1/2 Cup", RecipeId = 4 },
                        new { IngredientId = 21, Name = "Cubed Mozzarella", Quantity = "1/4 Cup", RecipeId = 4 },
                        new { IngredientId = 22, Name = "Basil", Quantity = "1/4 Cup", RecipeId = 4 },
                        new { IngredientId = 23, Name = "Provolone Cheese", Quantity = "1/2 Cup", RecipeId = 4 },
                        new { IngredientId = 24, Name = "Grated Parmesean Cheese", Quantity = "1/2 Cup", RecipeId = 4 },
                        new { IngredientId = 25, Name = "Olive Oil", Quantity = "1 Tbsp", RecipeId = 4 },
                        new { IngredientId = 26, Name = "Butter", Quantity = "1 Cup", RecipeId = 5 },
                        new { IngredientId = 27, Name = "White Sugar", Quantity = "1 Cup", RecipeId = 5 },
                        new { IngredientId = 28, Name = "Brown Sugar", Quantity = "1 Cup", RecipeId = 5 },
                        new { IngredientId = 29, Name = "Egg", Quantity = "2", RecipeId = 5 },
                        new { IngredientId = 30, Name = "Vanilla extract", Quantity = "2 Tsp", RecipeId = 5 },
                        new { IngredientId = 31, Name = "Baking Soda", Quantity = "1 Tsp", RecipeId = 5 },
                        new { IngredientId = 32, Name = "Hot Water", Quantity = "1 Tsp", RecipeId = 5 },
                        new { IngredientId = 33, Name = "Salt", Quantity = "1/2 Tsp", RecipeId = 5 },
                        new { IngredientId = 34, Name = "Flour", Quantity = "3 Cups", RecipeId = 5 },
                        new { IngredientId = 35, Name = "Chocolate Chips", Quantity = "2 Cups", RecipeId = 5 },
                        new { IngredientId = 36, Name = "Chopped Walnuts", Quantity = "1 Cup", RecipeId = 5 }
                    );
                });

            modelBuilder.Entity("ThePerfectBatch.Models.Recipe", b =>
                {
                    b.Property<int?>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Image");

                    b.Property<string>("Instructions");

                    b.Property<string>("Name");

                    b.Property<int>("RecipeTypeId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("RecipeId");

                    b.HasIndex("RecipeTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipe");

                    b.HasData(
                        new { RecipeId = 1, DateCreated = new DateTime(2019, 9, 12, 15, 22, 7, 178, DateTimeKind.Local), Image = "images/FrenchToast.jpg", Instructions = "1. Beat egg, vanilla and cinnamon in shallow dish. Stir in milk. 2. Dip bread in egg mixture, turning to coat both sides evenly. 3. Cook bread slices on lightly greased nonstick griddle or skillet on medium heat until browned on both sides.", Name = "French Toast", RecipeTypeId = 1, UserId = "00000000-ffff-ffff-ffff-ffffffffffff" },
                        new { RecipeId = 2, DateCreated = new DateTime(2019, 9, 12, 15, 22, 7, 182, DateTimeKind.Local), Image = "images/ChickpeaCrepe.jpg", Instructions = "1. In a blender, combine the garbanzo bean flour, water, salt and garlic powder. Blend on high until smooth. Allow to sit while you heat the skillet. 2. Lightly grease a large non-stick skillet and warm over medium-high heat. Pour in 1/4th of the batter at a time and cook until the edges start to bubble, about 3 minutes. Carefully flip and cook the opposite side until firm. Continue this step until you have 4 crepes. 3. Top each crepe with hummus, avocado, carrots, and 50/50 mixed greens. Serve with ranch dressing and enjoy!", Name = "Crepes", RecipeTypeId = 2, UserId = "00000000-ffff-ffff-ffff-ffffffffffff" },
                        new { RecipeId = 3, DateCreated = new DateTime(2019, 9, 12, 15, 22, 7, 182, DateTimeKind.Local), Image = "images/GrilledCheese.jpg", Instructions = "Preheat skillet over medium heat. Generously butter one side of a slice of bread. Place bread butter-side-down onto skillet bottom and add 1 slice of cheese. Butter a second slice of bread on one side and place butter-side-up on top of sandwich. Grill until lightly browned and flip over; continue grilling until cheese is melted. Repeat with remaining 2 slices of bread, butter and slice of cheese.", Name = "Grilled Cheese", RecipeTypeId = 3, UserId = "00000000-ffff-ffff-ffff-ffffffffffff" },
                        new { RecipeId = 4, DateCreated = new DateTime(2019, 9, 12, 15, 22, 7, 182, DateTimeKind.Local), Image = "images/ChickenParm.jpg", Instructions = "1. Preheat an oven to 450 degrees F (230 degrees C). 2. Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch. Season chicken thoroughly with salt and pepper. 3. Beat eggs in a shallow bowl and set aside. 4. Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside. 5. Place flour in a sifter or strainer; sprinkle over chicken breasts, evenly coating both sides. 6. Dip flour coated chicken breast in beaten eggs. Transfer breast to breadcrumb mixture, pressing the crumbs into both sides. Repeat for each breast. Set aside breaded chicken breasts for about 15 minutes. 7. Heat 1 cup olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken until golden, about 2 minutes on each side. The chicken will finish cooking in the oven. 8. Place chicken in a baking dish and top each breast with about 1/3 cup of tomato sauce. Layer each chicken breast with equal amounts of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle 1 to 2 tablespoons of Parmesan cheese on top and drizzle with 1 tablespoon olive oil. 9. Bake in the preheated oven until cheese is browned and bubbly, and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).", Name = "Chicken Parmesean", RecipeTypeId = 4, UserId = "00000000-ffff-ffff-ffff-ffffffffffff" },
                        new { RecipeId = 5, DateCreated = new DateTime(2019, 9, 12, 15, 22, 7, 182, DateTimeKind.Local), Image = "images/ChocolateChipCookie.jpg", Instructions = "1. Preheat oven to 350 degrees F (175 degrees C). 2. Cream together the butter, white sugar, and brown sugar until smooth. Beat in the eggs one at a time, then stir in the vanilla. Dissolve baking soda in hot water. Add to batter along with salt. Stir in flour, chocolate chips, and nuts. Drop by large spoonfuls onto ungreased pans. 3. Bake for about 10 minutes in the preheated oven, or until edges are nicely browned.", Name = "Chocolate Chip Cookies", RecipeTypeId = 5, UserId = "00000000-ffff-ffff-ffff-ffffffffffff" }
                    );
                });

            modelBuilder.Entity("ThePerfectBatch.Models.RecipeType", b =>
                {
                    b.Property<int>("RecipeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("RecipeTypeId");

                    b.ToTable("RecipeType");

                    b.HasData(
                        new { RecipeTypeId = 1, Name = "Breakfast" },
                        new { RecipeTypeId = 2, Name = "Brunch" },
                        new { RecipeTypeId = 3, Name = "Lunch" },
                        new { RecipeTypeId = 4, Name = "Dinner" },
                        new { RecipeTypeId = 5, Name = "Desert" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ThePerfectBatch.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ThePerfectBatch.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ThePerfectBatch.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ThePerfectBatch.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThePerfectBatch.Models.Ingredient", b =>
                {
                    b.HasOne("ThePerfectBatch.Models.Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ThePerfectBatch.Models.Recipe", b =>
                {
                    b.HasOne("ThePerfectBatch.Models.RecipeType", "RecipeType")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ThePerfectBatch.Models.ApplicationUser", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
